version: '3'

services:
  db:
    image: mongo
    ports:
      - 27017:27017
#  deploy:
#    replicas: 2


  lerna:
    image: yurikrupnik/lerna-examples_lerna
    build:
      context: .
    container_name: lerna
    deploy:
      replicas: 0

  app:
    image: yurikrupnik/lerna-examples_app
    build:
      context: packages/app
    container_name: app
    environment:
      - DEST_PORT=8000
      - PORT=9000
      - DESTINATION_HOST=http://gateway1
#      - USERS_ENDPOINT=http://localhost:7000
#      - for compose local
#      - DESTINATION_HOST=http://192.168.99.107 for compose cloud
#      - DOCKER_HOST=http://192.168.99.107
#      - HOST=http://192.168.99.107
#      - HOST=0.0.0.0
#      - host=0.0.0.0
#      - HOST=gateway1
#      - NODE_ENV_DOCKER=true
    ports:
      - 9000:9000
    command: npm run start
    depends_on:
      - db
      - lerna
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
